// Prioritized countries at the top
export const priorityCountries = [
    { code: 'US', name: 'United States', languages: ['en'] },
    { code: 'GB', name: 'United Kingdom', languages: ['en'] },
  ];
  
  // Rest of the countries
export const otherCountries = [
    { code: 'AF', name: 'Afghanistan', languages: ['ps', 'fa'] },
    { code: 'AL', name: 'Albania', languages: ['sq'] },
    { code: 'DZ', name: 'Algeria', languages: ['ar'] },
    { code: 'AR', name: 'Argentina', languages: ['es'] },
    { code: 'AU', name: 'Australia', languages: ['en'] },
    { code: 'AT', name: 'Austria', languages: ['de'] },
    { code: 'BE', name: 'Belgium', languages: ['nl', 'fr', 'de'] },
    { code: 'BR', name: 'Brazil', languages: ['pt'] },
    { code: 'CA', name: 'Canada', languages: ['en', 'fr'] },
    { code: 'CL', name: 'Chile', languages: ['es'] },
    { code: 'CN', name: 'China', languages: ['zh'] },
    { code: 'CO', name: 'Colombia', languages: ['es'] },
    { code: 'CZ', name: 'Czech Republic', languages: ['cs'] },
    { code: 'DK', name: 'Denmark', languages: ['da'] },
    { code: 'EG', name: 'Egypt', languages: ['ar'] },
    { code: 'FI', name: 'Finland', languages: ['fi'] },
    { code: 'FR', name: 'France', languages: ['fr'] },
    { code: 'DE', name: 'Germany', languages: ['de'] },
    { code: 'GR', name: 'Greece', languages: ['el'] },
    { code: 'HK', name: 'Hong Kong', languages: ['zh', 'en'] },
    { code: 'HU', name: 'Hungary', languages: ['hu'] },
    { code: 'IN', name: 'India', languages: ['hi', 'en'] },
    { code: 'ID', name: 'Indonesia', languages: ['id'] },
    { code: 'IE', name: 'Ireland', languages: ['en', 'ga'] },
    { code: 'IL', name: 'Israel', languages: ['he'] },
    { code: 'IT', name: 'Italy', languages: ['it'] },
    { code: 'JP', name: 'Japan', languages: ['ja'] },
    { code: 'KR', name: 'South Korea', languages: ['ko'] },
    { code: 'MY', name: 'Malaysia', languages: ['ms', 'en'] },
    { code: 'MX', name: 'Mexico', languages: ['es'] },
    { code: 'NL', name: 'Netherlands', languages: ['nl'] },
    { code: 'NZ', name: 'New Zealand', languages: ['en'] },
    { code: 'NO', name: 'Norway', languages: ['no'] },
    { code: 'PK', name: 'Pakistan', languages: ['ur', 'en'] },
    { code: 'PE', name: 'Peru', languages: ['es'] },
    { code: 'PH', name: 'Philippines', languages: ['tl', 'en'] },
    { code: 'PL', name: 'Poland', languages: ['pl'] },
    { code: 'PT', name: 'Portugal', languages: ['pt'] },
    { code: 'RO', name: 'Romania', languages: ['ro'] },
    { code: 'RU', name: 'Russia', languages: ['ru'] },
    { code: 'SA', name: 'Saudi Arabia', languages: ['ar'] },
    { code: 'SG', name: 'Singapore', languages: ['en', 'zh', 'ms'] },
    { code: 'ZA', name: 'South Africa', languages: ['en', 'af'] },
    { code: 'ES', name: 'Spain', languages: ['es'] },
    { code: 'SE', name: 'Sweden', languages: ['sv'] },
    { code: 'CH', name: 'Switzerland', languages: ['de', 'fr', 'it'] },
    { code: 'TW', name: 'Taiwan', languages: ['zh'] },
    { code: 'TH', name: 'Thailand', languages: ['th'] },
    { code: 'TR', name: 'Turkey', languages: ['tr'] },
    { code: 'AE', name: 'United Arab Emirates', languages: ['ar', 'en'] },
    { code: 'VN', name: 'Vietnam', languages: ['vi'] },
  ].sort((a, b) => a.name.localeCompare(b.name));